Add custom build type, custom keystore path and adjust for custom generated applicationIDs
cesarferreira/dryrun pull request #69
Opened 2016-11-18 13:59 UTC by pavlospt

Finally this one works... I have resorted to cherry-picking each commit and applying it after your upstream master latest changes.. I know that commit names are strange, but I want to make sure it passes the CI first and then I can squash them into one commit.

2016-11-19 10:07 UTC, cesarferreira requested changes

2016-11-19 10:07 UTC, cesarferreira commented on README.md
> +    --build_type BUILD_TYPE      Custom buildType (e.g. srv1, srv2)
add a shortcut for the build type and ident according to the other items

2016-11-19 10:07 UTC, cesarferreira commented on dryrun.gemspec
> +  spec.add_dependency 'adb-sdklib', '~> 0.0.3'
why bring back this lib?

2016-11-19 10:07 UTC, cesarferreira commented on lib/dryrun.rb
> +        opts.on('--build_type BUILD_TYPE', 'Custom buildType (e.g. srv1, srv2)') do |build_type|
add a shortcut

2016-11-19 10:07 UTC, cesarferreira commented on lib/dryrun.rb
> -      puts 'No devices attached, but I\'ll run anyway' if @devices.empty?
why remove this? it's informative to the user

2016-11-19 10:07 UTC, cesarferreira commented on lib/dryrun/android_project.rb
> +      root_module_builder = if @custom_module == nil
Please use a ternary operation

2016-11-19 10:07 UTC, cesarferreira commented on lib/dryrun/android_project.rb
> +        @root_module = 'app'  if @modules.first.first.gsub('/','') == 'app'
why do you assume the module will be called `app` ?

2016-11-19 10:07 UTC, cesarferreira commented on lib/dryrun/android_project.rb
> +      if intent_filter != nil and intent_filter.length != 0
why did you replace the code with this `non ruby standard` that does the same

2016-11-19 10:11 UTC, cesarferreira commented
Did you try to use a few features? It's not working on my side.

```

2016-12-11 23:01 UTC, cesarferreira commented
Everything alright @pavlospt ?

2016-12-12 08:03 UTC, pavlospt commented
Hey @cesarferreira, I have just been very busy lately and did not find some spare time to fix the issues. If you can leave it open till I can resolve them, it would be great. Otherwise, I completely understand if you just want to close it.

2016-12-12 10:25 UTC, cesarferreira commented
Take your time mate, just check if I haven't added the features you want to include meanwhile

2017-02-08 11:40 UTC, cesarferreira commented
I'll close it and will re-open when needed

2017-02-08 11:40 UTC, closed without merging

2017-02-08 12:00 UTC, pavlospt commented
Yeap, thanks, unfortunately I did not find the time to deal with it!